crawler/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .import views

app_name= 'crawler';
urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url('^$', views.landing, name='landing'),
    url(r'^webcrawler/', include('webcrawler.urls')),
]

webcrawler/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
app_name='webcrawler';

urlpatterns = [
    url(r'^link/$', views.webcrawler_link, name="webcrawler_link"),
    url(r'^result/$', views.webcrawler_result, name="webcrawler_result"),
    url(r'^images/$', views.webcrawler_images, name="webcrawler_images"),
    url(r'^links/$', views.webcrawler_links, name="webcrawler_links"),

]

webcrawler/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

crawler/views.py
from django.shortcuts import render

# Create your views here.
def landing(request, template_name='crawler/landing.html'):
    return render(request, template_name)

webcrawler/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests
from bs4 import BeautifulSoup




# Create your views here.

def webcrawler_link(request ,template_name='webcrawler/searchengine.html'):
    return render(request, template_name)

def webcrawler_result(request, template_name='webcrawler/result.html'):
    global img_tags
    global link_tags
    user_url = request.POST.get('searcher')

    ##right now i am hardcoding to gale . but in production we can make it dynamic as it takes loads of time

    html_source = requests.get(user_url)
    plain_text = html_source.text
    soup_format = BeautifulSoup(plain_text,'html.parser')
    img_tags = soup_format.find_all('img') ##getting all the images
    print(soup_format.encode("utf-8"))

    ##getting all hyperlinks
    link_tags = [a.get('href') for a in soup_format.find_all('a', href=True)]




    return render(request, template_name, {'user_url':user_url,'plain_text':plain_text,'img_tags':img_tags,'link_tags': link_tags})

def webcrawler_images(request, template_name='webcrawler/images.html'):
    global img_tags

    return render(request,template_name,{'img_tags':img_tags})


def webcrawler_links(request, template_name='webcrawler/links.html'):
    global link_tags

    return render(request,template_name,{'link_tags':link_tags})

templates/crawler/landing.html
<html>

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Web Crawler</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li class="active"><a href="{% url 'webcrawler:webcrawler_link'%}"> Web Crawler </a> </li>

    </ul>
  </div>
</nav>

<div class="container">
  <h3>Coming Soon ! </h3>
  <p>This example shows how to crawl websites</p>
</div>

</body>
</html>


</html>

templates/webcrawler/images.html
<html>

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>



  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
</head>


<body>


  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">

      <div class="navbar-header">
        <a class="navbar-brand" href="#">Web Crawler</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="nav-item"><a class="nav-link" href="/"> Home </a></li>


      </ul>

    </nav>

<B> I HAD ONLY LIMITED TIME SO COUDN'T PRETTY PRINT THE OUTPUT </B>

<br> </br>

<p> {{img_tags}} </p>


</html>

templates/webcrawler/links.html
<html>

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>



  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
</head>


<body>


  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">

      <div class="navbar-header">
        <a class="navbar-brand" href="#">Web Crawler</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="nav-item"><a class="nav-link" href="/"> Home </a></li>


      </ul>

    </nav>

<B> I HAD ONLY LIMITED TIME SO COUDN'T PRETTY PRINT THE OUTPUT </B>

<br> </br>


<p> {{link_tags}} </p>


</html>

templates/webcrawler/result.html
<html>

  <head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>



    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>


<body>


    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">


        <div class="navbar-header">
          <a class="navbar-brand" href="#">Web Crawler</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="nav-item"><a class="nav-link" href="/"> Home </a></li>


        </ul>

      </nav>


  <div class="container">
    <div class="row">
      <div class="col-md-12">



        <h1>
          <strong> The given Webpage is  {{user_url}}  </strong>

          <br> </br>

          <strong>  I had limited time to pretty print the output </strong>

        </h1>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
          <a href="{% url 'webcrawler:webcrawler_images' %}" class="tile purple">
            <h3 class="title">Images</h3>
            <p>Get all images here</p>
          </a>
      </div>
      <div class="col-sm-4">
          <a href="{% url 'webcrawler:webcrawler_links' %}" class="tile orange">
            <h3 class="title">Links</h3>
            <p>Get All links here.</p>
          </a>
      </div>

    </div>

  </div>
</div>

<h1>
<strong > Printing Raw output for reference , however i can use this data to do analysis and push it to db </strong>
</h1>
<p> {{plain_text}} </p>


<p> The images are </P>


<p> {{img_tags}} </p>


<p> The links are </p>

<p> {{link_tags}} </p>





</body>


</html>
<style>

  @import "bourbon";

$color_purple: #5133AB;
$color_red: #AC193D;
$color_orange: #DC572E;
$color_green: #00A600;
$color_blue: #2672EC;

$base_font_size: 14px;
$base_line_height: 1.5em;
$text_font_family: 'Open Sans', "Segoe UI", Frutiger, "Frutiger Linotype", "Dejavu Sans", "Helvetica Neue", Arial, sans-serif;
$display_font_family: 'Open Sans', "Segoe UI", Frutiger, "Frutiger Linotype", "Dejavu Sans", "Helvetica Neue", Arial, sans-serif;

body {
	font-family: $text_font_family;
	font-size: $base_font_size;
	line-height: $base_line_height;
	font-weight: 400;
}

p, span, a, ul, li, button {
	font-family: inherit;
	font-size: inherit;
	font-weight: inherit;
	line-height: inherit;
}

strong {
	font-weight: 600;
}

h1, h2, h3, h4, h5, h6 {
	font-family: $display_font_family;
	line-height: $base_line_height;
	font-weight: 300;
}

strong {
  font-weight: 400;
}

.tile {
  width: 100%;
	display: inline-block;
	box-sizing: border-box;
	background: #fff;
	padding: 20px;
	margin-bottom: 10px;

  .title {
		margin-top: 0px;
	}

  &.purple, &.blue, &.red, &.orange, &.green {
    color: #fff;
  }

  &.purple {
    background: $color_purple;

		&:hover {
			background: darken($color_purple, 10%);
		}
  }

  &.red {
    background: $color_red;

		&:hover {
			background: darken($color_red, 10%);
		}
  }

  &.green {
    background: $color_green;

		&:hover {
			background: darken($color_green, 10%);
		}
  }

  &.blue {
    background: $color_blue;

		&:hover {
			background: darken($color_blue, 10%);
		}
  }

  &.orange {
    background: $color_orange;

		&:hover {
			background: darken($color_orange, 10%);
		}
  }
}

</style>

templates/webcrawler/searchengine.html
<html>
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>



  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
</head>

<!------ Include the above in your HEAD tag ---------->
<body>

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">

      <div class="navbar-header">
        <a class="navbar-brand" href="#">Web Crawler</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="nav-item"><a class="nav-link" href="/"> Home </a></li>


      </ul>

  </nav>

<div class="container">
    <br/>
  <div class="row justify-content-center">
      <div class="col-12 col-md-10 col-lg-8">
          <form class="card card-sm" action ="{% url 'webcrawler:webcrawler_result' %}"  method="POST"  id="form1" >
              {% csrf_token %}
              <div class="card-body row no-gutters align-items-center">
                  <div class="col-auto">
                      <i class="fas fa-search h4 text-body"></i>
                  </div>
                  <!--end of col-->
                  <div class="col">
                      <input class="form-control form-control-lg form-control-borderless" type="search" name = "searcher" placeholder="Search topics or keywords">
                  </div>
                  <!--end of col-->
                  <div class="col-auto">
                      <button class="btn btn-lg btn-success" type="submit">Search</button>
                  </div>
                  <!--end of col-->
              </div>
          </form>
      </div>
      <!--end of col-->
  </div>
</div>

</body>
<style>
.form-control-borderless {
    border: none;
}

.form-control-borderless:hover, .form-control-borderless:active, .form-control-borderless:focus {
    border: none;
    outline: none;
    box-shadow: none;
}
</style>
</html>